### ISSUE TITLE
【fixbug】fn:: wechatMenu() 方法有报错

### ISSUE THREAD

**Issue by ferocknew** [ferocknew/wechatGo-web#4]
/application/index/controller/Wechat.php
fn:: wechatMenu() 

![image](https://user-images.githubusercontent.com/2178683/74096774-2809ae00-4b3e-11ea-9314-d0691493e300.png)

**Comment by lyx32609** [comment]
微信菜单添加弹窗验证码，修改木有菜单报错已提交PR

**Comment by ferocknew** [comment]
已修复
